### ISSUE TITLE
New color painting/matching criterion

### ISSUE THREAD

**Issue by mbaumer** [drphilmarshall/OM10#25]
- Do matching based on redshift alone, subject to further cuts:
  - ZSRC < 4.5
  - ZLENS < 3
  - 200 < VELDISP < 300 (target matches to most massive galaxies)

**Comment by mbaumer** [comment]
Hey @drphilmarshall , I'm using my own naive redshift matching, which just finds the lens/qso in the sloan reference with the closest redshift to each simulated object and assigns the sim that color. Quasar painting looks good (there had been a bug before--on my end, not Adri's), but for the lenses there are a good number of color outliers at low redshift, especially in g-r for z < 0.2 -- any thoughts?

![image](https://cloud.githubusercontent.com/assets/7607631/8674316/0ace2732-2a35-11e5-99ea-1baeb5366de0.png)

**Comment by drphilmarshall** [comment]
Looks like some blue galaxies, perhaps with spatially unresolved high
rotation velocities? I suggest cutting them out with a g-r plus i-r color
box (they seem to form a sequence at r-i ~ 0.0 and g-r >~ 0.2 or so) - what
do you think?

**Comment by mbaumer** [comment]
OK, I put in cuts demanding g-r < 3, r-i > 0, and i-z > 0. The plots look much better, but I think now we should discuss the issue of high-redshift colors (column 1 of attached plot).

Right now, my redshift matching is grabbing the colors of the object with the closest z, but for all objects with z > ~1, this is simply the highest redshift object in the reference catalog, meaning all lenses past z=1 have exactly the same color. This isn't ideal, but do you think it's ok for the first pass? I could put in some (true) variation by randomly choosing colors from the N closest reference redshifts or something... 

![image](https://cloud.githubusercontent.com/assets/7607631/8697011/674b8f36-2ae9-11e5-916c-7bf9a32ed21c.png)

**Comment by aagnello** [comment]
In fact, for my needs I bypassed it because I was *drawing* from a distribution with interpolated mean and interpolated covariances. I think this alleviates the problem because it blurs things. If you want to improve on it, besides adding higher-z galaxies, you can try to draw from a sort of de-trended distribution:
-- use spectral templates (Mannucci; Kinney and Calzetti; ...) to set the average colour with redshift
-- use them to determine the average colour as fnct.of z
-- in the detrended colours (swarm-minus-template) at 0<z<1, check if the std.dev. in colour varies with z, extrapolate it to higher z
-- given a galaxy at z>1, draw its magnitudes/colours from the template plus a scatter given by the extrapolated std.dev.
Same goes for the i-band magnitude as fnct. of z and sigma (or whatever magnitude you're using as the reference one).

**Comment by drphilmarshall** [comment]
Let's go with Adri's first suggestion and investigate templates. I think we'll end up with a more flexible system.
